### ISSUE TITLE
questions about some parameters in the code

### ISSUE THREAD

**Issue by Liu-YT** [zhuligs/fplib#1]
Hello,  recently read your code on the periodic calculation part. What is the meaning and how to set the three parameters `lmax`, `cutoff` and `natx` (the func `get_fp_periodic`)?

**Comment by zhuligs** [comment]
lmax is the maximum angular moment of the Gaussian atomic orbitals. There are two choices for lmax: only s orbital is used when lmax=0; both s and p orbitals are used when lmax = 1. For practice, I usually use lmax = 0.

'cutoff' is used to define the cutoff radius when constructing the cluster. And natx is the maximum number of atoms within the cluster. To obtain accurate results, it usually requires ~100 atoms in each cluster.  You can play with cutoff to get a suitable value. 

I recommend you to read the paper that describes this crystal fingerprinting method. 
[Zhu et al. - 2016 - A fingerprint based metric for measuring similarities of crystalline structures.pdf](https://github.com/zhuligs/fplib/files/3961717/Zhu.et.al.-.2016.-.A.fingerprint.based.metric.for.measuring.similarities.of.crystalline.structures.pdf)
