### ISSUE TITLE
questions about some parameters in the code

### ISSUE THREAD

**Issue by gbmumumu** [zhuligs/fplib#2]
Hi, I don’t quite understand some parameters in the code, for example, i want obtain the crystal 
 fingerprint about Ag2Ca:
Ag2Ca
1.0
     7.26000000     0.00000000     0.00000000
     0.00000000     4.68000000     0.00000000
     0.00000000     0.00000000     8.14000000
  Ag  Ca
  8  4
Direct
     0.80000000     0.75000000     0.92000000
     0.80000000     0.25000000     0.08000000
     0.20000000     0.25000000     0.08000000
     0.20000000     0.75000000     0.92000000
     0.30000000     0.25000000     0.42000000
     0.30000000     0.75000000     0.58000000
     0.70000000     0.75000000     0.58000000
     0.70000000     0.25000000     0.42000000
     0.00000000     0.75000000     0.35500000
     0.00000000     0.25000000     0.64500000
     0.50000000     0.25000000     0.85500000
     0.50000000     0.75000000     0.14500000
I installed  fppy and try to use func fppy.fp_periodic(lattice, position, atom_type, znu,  lmax, natx, cutoff) to get result，Is ’atom_type‘ means [Ag, Ca] or it's atomic number [47,20] or[47,47...] ? and  what does 'znu' mean?

**Comment by zhuligs** [comment]
In your case, atom_type means [1,1,1,1,1,1,1,1,2,2,2,2]. 

BTW. I have updated a new version, which should be more user-friendly. Note, Python 3 is needed. You can find an example in the examples directory.
